sudo apt-get install php7.3-bcmath -y
sudo apt-get install php7.3-bz2 -y
sudo apt-get install php7.3-calendar -y
sudo apt-get install php7.3-ctype -y
sudo apt-get install php7.3-curl -y
sudo apt-get install php7.3-dom -y
sudo apt-get install php7.3-enchant -y
sudo apt-get install php7.3-exif -y
sudo apt-get install php7.3-fileinfo -y
sudo apt-get install php7.3-ftp -y
sudo apt-get install php7.3-gd -y
sudo apt-get install php7.3-gettext -y
sudo apt-get install php7.3-gmp -y
sudo apt-get install php7.3-iconv -y
sudo apt-get install php7.3-intl -y
sudo apt-get install php7.3-json -y
sudo apt-get install php7.3-ldap -y
sudo apt-get install php7.3-mbstring -y
sudo apt-get install php7.3-mysqli -y
sudo apt-get install php7.3-mysqlnd -y
sudo apt-get install php7.3-opcache -y
sudo apt-get install php7.3-pdo -y
sudo apt-get install php7.3-phar -y
sudo apt-get install php7.3-posix -y
sudo apt-get install php7.3-pspell -y
sudo apt-get install php7.3-readline -y
sudo apt-get install php7.3-shmop -y
sudo apt-get install php7.3-simplexml -y
sudo apt-get install php7.3-soap -y
sudo apt-get install php7.3-sockets -y
sudo apt-get install php7.3-sqlite3 -y
sudo apt-get install php7.3-sysvmsg -y
sudo apt-get install php7.3-sysvsem -y
sudo apt-get install php7.3-sysvshm -y
sudo apt-get install php7.3-wddx -y
sudo apt-get install php7.3-xml -y
sudo apt-get install php7.3-xsl -y
sudo apt-get install php7.3-recode -y
sudo apt-get install php7.3-dba -y
sudo apt-get install php7.3-imap -y
sudo apt-get install php7.3-interbase -y
sudo apt-get install php7.3-odbc -y
sudo apt-get install php7.3-pgsql -y
sudo apt-get install php7.3-tidy -y
sudo apt-get install php7.3-zip -y
